global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
      - targets:
        - alertmanager:9093
        - localhost:9093

rule_files:
  - "/etc/prometheus/rules.d/*.yml"

# scrape_configs:
#   - job_name: 'metrics-platform'
#     scrape_interval: 60s
#     scrape_timeout: 25s

#     honor_labels: false
#     metrics_path: '/federate'
    

#     params:
#       'match[]':
#         - '{__name__="ops_application_succcess_percentage_rate_1m"}'
#         - '{__name__="ops_environment_info"}'
#         - '{__name__="ops_request_total"}'


#     static_configs:
#       - targets:
#         - 'metricsplat.staging.espigah.io:80'
